version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    # イメージ名を指定
    image: chatgpt

    # localとcontainer間のファイルを同期させる
    # ${local}:${container}
    volumes:
      - .:/chatgpt

    # Overrides default command so things don't shut down after the process ends.
    command: /bin/zsh -c "while sleep 1000; do :; done"
